name: Cleanup Flex testing endpoint

on:
    workflow_call:

jobs:
    flex-cleanup:
        name: Cleanup Flex testing endpoint
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2

            -
                name: Cleanup Flex testing endpoint
                run: |
                    git push origin :flex/pull-${{ github.event.number }} || true
